import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar101, Navbar1Defaults } from "@/components/UI/NavBar";
import { Footer2, Footer2Defaults } from "@/components/UI/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar101 {...Navbar1Defaults} />
        {/* <Navbar1 /> */}
        {children}
        <Footer2 {...Footer2Defaults} />
      </body>
    </html>
  );
}
